Change how the callback queue is cleared from the finalizer.
In Ruby 3.1.1, accessing callback_queue from a finalizer causes a "undefined local variable or method `callback_queue' for FiniteMachine::Observer:Class (NameError)", and callback_queue is never cleaned up. However, making the finalizer an instance method rather than a class method throws a warning about improper use of finalizers.

The fix is borrowed from a Github issue found at https://github.com/appsignal/rdkafka-ruby/pull/160/files.